import { Journey, FamilyMember, StatItem, GeofencePlace } from '@/types';

export const CURRENT_USER = {
  id: 'usr_alex',
  name: 'Alex Rivera',
  email: 'alex.rivera@familytrack.app',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
  familyCircleName: 'Rivera Family',
  joinedDate: 'January 2025',
};

export const TODAY_STATS: StatItem[] = [
  {
    id: 'distance',
    label: "Today's Distance",
    value: '24.8',
    unit: 'km',
    change: '+14%',
    trend: 'up',
    subtext: 'vs yesterday (21.7 km)',
  },
  {
    id: 'journeys',
    label: "Today's Journeys",
    value: 3,
    unit: 'trips',
    change: 'On track',
    trend: 'neutral',
    subtext: 'All 3 shared with Family',
  },
  {
    id: 'travel_time',
    label: 'Travel Time',
    value: '1h 15m',
    change: '-8 mins',
    trend: 'up',
    subtext: 'Avoided peak traffic',
  },
  {
    id: 'stops',
    label: 'Number of Stops',
    value: 6,
    unit: 'stops',
    change: 'Recorded',
    trend: 'neutral',
    subtext: 'School, Office & Market',
  },
];

export const MOCK_JOURNEYS: Journey[] = [
  {
    id: 'jrn_001',
    title: 'Morning Office Commute',
    category: 'Commute',
    distanceKm: 14.2,
    durationMins: 28,
    date: 'Today',
    startTime: '08:15 AM',
    endTime: '08:43 AM',
    stopCount: 2,
    status: 'completed',
    privacyLevel: 'family',
    startLocation: '742 Evergreen Terrace (Home)',
    endLocation: 'Downtown Financial Hub',
    safetyScore: 98,
    speedAvgKmH: 30.4,
    memberName: 'Alex Rivera',
    notes: 'Smooth highway drive. No delays reported.',
  },
  {
    id: 'jrn_002',
    title: 'School Drop-off & Coffee Stop',
    category: 'School Run',
    distanceKm: 5.6,
    durationMins: 18,
    date: 'Today',
    startTime: '07:45 AM',
    endTime: '08:03 AM',
    stopCount: 2,
    status: 'completed',
    privacyLevel: 'family',
    startLocation: '742 Evergreen Terrace (Home)',
    endLocation: 'Lincoln Academy',
    safetyScore: 100,
    speedAvgKmH: 22.1,
    memberName: 'Alex Rivera',
  },
  {
    id: 'jrn_003',
    title: 'Evening Run at Riverside Trail',
    category: 'Running',
    distanceKm: 5.0,
    durationMins: 29,
    date: 'Yesterday',
    startTime: '06:10 PM',
    endTime: '06:39 PM',
    stopCount: 1,
    status: 'completed',
    privacyLevel: 'private',
    startLocation: 'North Park Entrance',
    endLocation: 'River Loop Bridge',
    safetyScore: 99,
    speedAvgKmH: 10.3,
    memberName: 'Alex Rivera',
    notes: 'Personal fitness session.',
  },
  {
    id: 'jrn_004',
    title: 'Grocery & Pharmacy Pickup',
    category: 'Personal',
    distanceKm: 7.8,
    durationMins: 34,
    date: 'Yesterday',
    startTime: '04:30 PM',
    endTime: '05:04 PM',
    stopCount: 3,
    status: 'completed',
    privacyLevel: 'family',
    startLocation: 'Downtown Office',
    endLocation: '742 Evergreen Terrace (Home)',
    safetyScore: 95,
    speedAvgKmH: 24.5,
    memberName: 'Sarah Rivera',
  },
  {
    id: 'jrn_005',
    title: 'Weekend Family Trail Ride',
    category: 'Cycling',
    distanceKm: 32.4,
    durationMins: 112,
    date: 'Sep 21, 2026',
    startTime: '09:00 AM',
    endTime: '10:52 AM',
    stopCount: 4,
    status: 'completed',
    privacyLevel: 'circle',
    startLocation: 'Blue Ridge Trailhead',
    endLocation: 'Summit Overlook Cafe',
    safetyScore: 100,
    speedAvgKmH: 17.3,
    memberName: 'Rivera Family',
  },
];

export const MOCK_FAMILY_MEMBERS: FamilyMember[] = [
  {
    id: 'fam_001',
    name: 'Sarah Rivera',
    role: 'Spouse',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=250&q=80',
    status: 'at_work',
    statusText: 'At Innovation Campus',
    lastActive: '5 mins ago',
    batteryLevel: 88,
    sharingMode: 'journey_only',
    color: '#10b981', // Emerald
  },
  {
    id: 'fam_002',
    name: 'Marcus Rivera',
    role: 'Son',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    status: 'in_transit',
    statusText: 'In Transit • Bus to Soccer Practice',
    lastActive: 'Just now',
    batteryLevel: 64,
    sharingMode: 'journey_only',
    activeJourneyTitle: 'After School Bus Route',
    color: '#06b6d4', // Cyan
  },
  {
    id: 'fam_003',
    name: 'Emma Rivera',
    role: 'Daughter',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=250&q=80',
    status: 'at_school',
    statusText: 'At Lincoln Academy',
    lastActive: '12 mins ago',
    batteryLevel: 92,
    sharingMode: 'journey_only',
    color: '#8b5cf6', // Purple
  },
  {
    id: 'fam_004',
    name: 'Robert Rivera',
    role: 'Parent',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80',
    status: 'at_home',
    statusText: 'At Evergreen Terrace',
    lastActive: '1 hour ago',
    batteryLevel: 45,
    sharingMode: 'on_demand',
    color: '#f59e0b', // Amber
  },
];

export const MOCK_GEOFENCE_PLACES: GeofencePlace[] = [
  {
    id: 'geo_01',
    name: 'Home (Evergreen Terrace)',
    address: '742 Evergreen Terrace, Springfield',
    category: 'home',
    radiusMeters: 150,
    activeMembersCount: 1,
  },
  {
    id: 'geo_02',
    name: 'Tech Hub Office',
    address: '100 Innovation Way, Suite 400',
    category: 'work',
    radiusMeters: 200,
    activeMembersCount: 1,
  },
  {
    id: 'geo_03',
    name: 'Lincoln Academy',
    address: '45 Educational Blvd',
    category: 'school',
    radiusMeters: 250,
    activeMembersCount: 1,
  },
  {
    id: 'geo_04',
    name: 'Metro Sports Complex',
    address: '88 Athletic Drive',
    category: 'gym',
    radiusMeters: 300,
    activeMembersCount: 0,
  },
];

export const MOCK_ANALYTICS = {
  weeklyDistance: [
    { day: 'Mon', distance: 18.4, trips: 2 },
    { day: 'Tue', distance: 26.1, trips: 4 },
    { day: 'Wed', distance: 24.8, trips: 3 },
    { day: 'Thu', distance: 19.5, trips: 3 },
    { day: 'Fri', distance: 31.0, trips: 5 },
    { day: 'Sat', distance: 42.5, trips: 2 },
    { day: 'Sun', distance: 12.0, trips: 1 },
  ],
  transportSplit: [
    { mode: 'Driving', percentage: 62, color: '#10b981' },
    { mode: 'Transit', percentage: 18, color: '#06b6d4' },
    { mode: 'Cycling', percentage: 12, color: '#3b82f6' },
    { mode: 'Walking', percentage: 8, color: '#a855f7' },
  ],
  privacyScore: 99.4,
  ecoSavingsKgCO2: 14.8,
  totalJourneysThisMonth: 48,
};
